### ISSUE TITLE
No deduction child handler for BinaryExpression

### ISSUE THREAD

**Issue by schas002** [vsl-lang/VSL#59]
What is 2 + 3?

```
vsl> 2 + 3
TypeError: No deduction child handler for BinaryExpression
 at RootResolver.vslGetChild [as getChild] (https://staging.vihan.org/VSL/app/main.bundle.js:11851:19)
  at RootResolver.resolve (https://staging.vihan.org/VSL/app/main.bundle.js:24249:30)
   at TypeDeductExpression.modify (https://staging.vihan.org/VSL/app/main.bundle.js:13125:85)
    at VSLTransformer.transform_once (https://staging.vihan.org/VSL/app/main.bundle.js:8173:28)
     at VSLTransformer.transform (https://staging.vihan.org/VSL/app/main.bundle.js:8139:35)
      at VSLTransformer.didUpdateQueue (https://staging.vihan.org/VSL/app/main.bundle.js:8088:22)
       at VSLTransformer.appendNodeQueue (https://staging.vihan.org/VSL/app/main.bundle.js:8065:18)
        at VSLTransformer.receivedNode (https://staging.vihan.org/VSL/app/main.bundle.js:8042:18)
         at VSLTransformer.processNode (https://staging.vihan.org/VSL/app/main.bundle.js:14064:22)
          at VSLTransformer.processNode (https://staging.vihan.org/VSL/app/main.bundle.js:13595:140)
vsl> // ...
Root
```

- **Tested in**: the web version of VSL at staging.vihan.org, which is **`v0.0.2-alpha.3`**.

**Comment by schas002** [comment]
`3 - 2`, `2 * 3`, `3 / 2` all return the same error. Apparently, VSL doesn't know math :|

**Comment by vihanb** [comment]
For this we need recursive type which can't be do until @somebody1234's [branch](/vsl-lang/VSL/tree/merge/command-chain-develop)

**Comment by schas002** [comment]
Last commit on ***12 Jul*** :scream:

At that rate, @somebody1234, it might never get merged XD I hope it does
